[package]
name = "codigo"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.28"
nalgebra-glm = "0.19"
pixels = "0.14.0"
winit = "0.27"
image = "0.23"
rayon = "1.5"
fastnoise-lite = "1.1.1" # Actualizado a la última versión disponible